sudo: required
services:
  - docker

before_install:
  - docker build -t hamishdocker/docker-react -f Dockerfile.dev .

script: 
 - docker run -e CI=true hamishdocker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  name: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-550515002419"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"