version: "3"
services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:3000"
    volumes:
      - /usr/apps/node_modules
      - .:/usr/apps
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/apps/node_modules
      - .:/usr/apps
    command: ["npm","run","test"]
